### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by admtan** [mqce/akizuki-permanent#1]
Hello! I have been using your project quite conveniently and appreciate your work. However, I noticed a concern and wanted to create an issue for it.

It seems that the project is missing a LICENSE file, and the copyright information is not explicitly stated. Is this intentional? If you permit modification and redistribution of the code, such as forking, I kindly suggest applying an appropriate open-source license. Even if you only allow code referencing or auditing without permitting modifications, it would still be helpful to have the copyright information clearly stated.

Thank you!

**Comment by mqce** [comment]
Thanks.
Added LICENSE file.
