### ISSUE TITLE
数日前から正常に動作しない

### ISSUE THREAD

**Issue by elfham** [mqce/akizuki-permanent#2]
ふわっとしたタイトルですみませんが、数日前から正常に動作しなくなっているようです。
ヘッダ部分が真っ白で何も表示されなくなり、
拡張機能の各種機能 (全てかどうかは未確認です) も使用できなくなっているようです。

**Comment by nanase** [comment]
同じ現象が私の環境でも発生して困っており、原因を調べてみました。
ローカルビルド（`npm run start` で生成されたもの）で実行したところ、以下のエラーが出ていることがわかりました。

![image](https://github.com/mqce/akizuki-daisuki/assets/1804744/9d1dfd2b-48ec-485e-8ca3-9525ee33fe91)

コード上では [Bookmark.js](https://github.com/mqce/akizuki-daisuki/blob/main/src/modules/Bookmark.js#L12) にあたります。 [Sanitizer](https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer) は Chrome 105 で実装されたAPIですが、119で[非推奨とされ](https://developer.chrome.com/blog/sanitizer-api-deprecation/)、[削除](https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer#browser_compatibility)されました。非推奨の経緯からもこのAPIが元の状態に復活する見込みはなさそうで、拡張機能側の更新が必要と思われます。

（追記） 上記の Sanitizer を使ってHTMLの書き換えに使っている [setHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/setHTML) も Sanitizer と同様にChrome 119で[削除](https://developer.mozilla.org/en-US/docs/Web/API/Element/setHTML#browser_compatibility)されており機能しません。

--- 

@mqce 対応の見込みはありますか？

**Comment by mqce** [comment]
修正してchromeストアにアップしました。審査が通り次第公開されます。

**Comment by elfham** [comment]
1.0.1 の更新が降ってきたようなので試してみましたが、問題無さそうでした。
対応ありがとうございました。

**Comment by kurokurokuro1** [comment]
1.0.1に更新したけど在庫表示の横にnullと表示されて在庫の自動表示は改善されてません。
他の動作(ヘッダ画像表示・お気に入り・カートボタン操作)は問題なさそうです。

**Comment by mqce** [comment]
@kurokurokuro1 
v1.0.2で修正しました。

**Comment by kurokurokuro1** [comment]
> @kurokurokuro1 v1.0.2で修正しました。

早急な対応ありがとうございます！

**Comment by kurokurokuro1** [comment]
1.0.2に更新後、無事在庫表示が正常に表示されることを確認しました。
